In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parents[1]
sys.path.append(str(PROJECT_ROOT))


from src.utils.import_util import *
from src.utils.data_load_util import *

Data Loading

In [2]:
titanic_df = pd.read_csv(data_source)

Inspecting data

In [3]:
titanic_df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Data Description

In [4]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   891 non-null    int64
 1   PassengerId  891 non-null    int64
 2   Survived     891 non-null    int64
 3   Pclass       891 non-null    int64
 4   Name         891 non-null    object
 5   Sex          891 non-null    object
 6   Age          714 non-null    float64
 7   SibSp        891 non-null    int64
 8   Parch        891 non-null    int64
 9   Ticket       891 non-null    object
 10  Fare         891 non-null    float64
 11  Cabin        204 non-null    object
 12  Embarked     889 non-null    object
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

In [5]:
titanic_df.isna().sum()

Unnamed: 0       0
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
titanic_df[titanic_df.duplicated()==True]

Empty DataFrame
Columns: [Unnamed: 0, PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [7]:
# if there were duplicated data
titanic_df.drop_duplicates(inplace=True)

In [8]:
# then I will run duplicated to check that the duplicated data are now removed
titanic_df.duplicated().sum()

np.int64(0)

In [9]:
titanic_df.describe()

,Unnamed: 0,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,445.000000,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,222.500000,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,445.000000,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,667.500000,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,890.000000,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [10]:
titanic_df[titanic_df['Age'].isna()==True]

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [11]:
# df_age_group = titanic_df.groupby(['Sex', 'PClass'],)['Age'].median()

In [12]:
titanic_df['Age'] = titanic_df.groupby(
    ['Sex', 'Pclass']
)['Age'].transform(
    lambda x: x.fillna(x.median())
)

In [13]:
titanic_df.isna().sum()

Unnamed: 0       0
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [14]:
titanic_df.drop(columns=['Cabin'], inplace=True)

In [15]:
# EMBARKED
titanic_df['Embarked'] = titanic_df['Embarked'].fillna(
    titanic_df['Embarked'].mode()[0]
)

In [16]:
titanic_df.describe()

,Unnamed: 0,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,445.000000,446.000000,0.383838,2.308642,29.112424,0.523008,0.381594,32.204208
std,257.353842,257.353842,0.486592,0.836071,13.304424,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,222.500000,223.500000,0.000000,2.000000,21.500000,0.000000,0.000000,7.910400
50%,445.000000,446.000000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,667.500000,668.500000,1.000000,3.000000,36.000000,1.000000,0.000000,31.000000
max,890.000000,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [17]:
titanic_df.isna().sum()

Unnamed: 0     0
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

Now that the dataset is clean, we move on to regression analysis and modeling

All my import comes from the utils/import_util.py to keep the code clean

Since I am trying to predict the passengers that survived, my target variable is Surviced

In [18]:
# Target
y = titanic_df['Survived']

# Features
X = titanic_df.drop(['Survived'], axis=1)

Columns not very useful
Name - too unique, Ticket - messy text, PassenderId - identifier

In [19]:
# Drop unnecessary columns
X = X.drop(['Name', 'Ticket', 'PassengerId'], axis=1)

In [20]:
X = pd.get_dummies(
    X,
    columns=X.select_dtypes(include=["object"]).columns.tolist(),
    drop_first=True
)

In [21]:
# Converting the data to float
X = X.astype(float)

In [22]:
x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

In [23]:
lin_reg = LinearRegression()
lin_reg.fit(x_train,y_train)

LinearRegression()

# Linear regression is not the best model for this type of dataset
# WHY? Survived = 0 or 1 - Hence, Classification

In [24]:
# A better model here is Logic Regression
# why? - Linear regression predicts continious values
# Logistic Regression predicts Categories/classes

In [25]:
lin_reg = LinearRegression()
lin_reg.fit(x_train,y_train)

LinearRegression()

In [26]:
log_rig = LogisticRegression(max_iter=1000)
log_rig.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [27]:
predictions = log_rig.predict(x_test)

In [28]:


accuracy_score(y_test, predictions)

0.8134328358208955

In [29]:
y_pred_train = log_rig.predict(x_train)

In [30]:
mean_squared_error(y_train, y_pred_train)

0.1942215088282504

In [31]:
r2_score(y_train, y_pred_train)

0.16751700680272097

In [32]:
y_pred_test = log_rig.predict(x_test)
print(mean_squared_error(y_test, y_pred_test))
print(r2_score(y_test, y_pred_test))

0.1865671641791045
0.23107821196993172